export const LOAD_PEOPLE_SUCCESS = "LOAD_PEOPLE_SUCCESS";
export const LOAD_PERSON_SUCCESS = "LOAD_PERSON_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
